CREATE TABLE cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(255) NOT NULL,
    documento       VARCHAR(14) NOT NULL,
    cep             VARCHAR(8) NOT NULL,
    logradouro      VARCHAR(255) NOT NULL,
    complemento     VARCHAR(255),
    bairro          VARCHAR(255) NOT NULL,
    cidade          VARCHAR(255) NOT NULL,
    uf              VARCHAR(2) NOT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT uk_cliente_documento UNIQUE (documento)
);

CREATE TABLE unidade_consumidora (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          BIGINT NOT NULL,
    nome                VARCHAR(255) NOT NULL,
    numero_instalacao   VARCHAR(50) NOT NULL,
    cep                 VARCHAR(8) NOT NULL,
    logradouro          VARCHAR(255) NOT NULL,
    complemento         VARCHAR(255),
    bairro              VARCHAR(255) NOT NULL,
    cidade              VARCHAR(255) NOT NULL,
    uf                  VARCHAR(2) NOT NULL,
    CONSTRAINT fk_uc_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT uk_uc_numero_instalacao UNIQUE (numero_instalacao)
);

CREATE INDEX idx_cliente_created_at ON cliente (created_at DESC);
CREATE INDEX idx_cliente_ativo ON cliente (ativo);
